[project]
name = "neural-network-applications"
version = "0.1.0"
description = "Details and code for constructing learning algorithms through artificial neural networks."
readme = "README.md"
requires-python = ">=3.12"
dependencies = []
